In [3]:
import numpy as np

In [4]:
a = np.array([2, 3, 4])
print(a)

[2 3 4]


In [5]:
a.dtype

dtype('int64')

In [6]:
b = np.array([1.2, 3.5, 5.1])
print(b)
b.dtype
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b)
b.dtype


[1.2 3.5 5.1]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


dtype('float64')

In [7]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:

np.ones((2, 3, 4))
np.dtype('float32')
print(np.ones((2, 3), dtype=np.float32))
print(np.dtype('float64'))

[[1. 1. 1.]
 [1. 1. 1.]]
float64


In [9]:
np.empty((2, 3), dtype=str)
np.arange(10, 30, .3)

array([10. , 10.3, 10.6, 10.9, 11.2, 11.5, 11.8, 12.1, 12.4, 12.7, 13. ,
       13.3, 13.6, 13.9, 14.2, 14.5, 14.8, 15.1, 15.4, 15.7, 16. , 16.3,
       16.6, 16.9, 17.2, 17.5, 17.8, 18.1, 18.4, 18.7, 19. , 19.3, 19.6,
       19.9, 20.2, 20.5, 20.8, 21.1, 21.4, 21.7, 22. , 22.3, 22.6, 22.9,
       23.2, 23.5, 23.8, 24.1, 24.4, 24.7, 25. , 25.3, 25.6, 25.9, 26.2,
       26.5, 26.8, 27.1, 27.4, 27.7, 28. , 28.3, 28.6, 28.9, 29.2, 29.5,
       29.8])

In [10]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [11]:
np.linspace(0, 2, 10) 

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [12]:
print(np.pi)

3.141592653589793


In [13]:
x = np.linspace(0, 2 * np.pi, 10)
print(x)
y= np.sin(x)
print(y)

[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]
[ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]


In [14]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
print(arr1)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr2)
print(arr1.dtype)
print(arr2.dtype)
print(arr1.astype(np.int32))
print(arr2.astype(np.float64))
print(arr1 + arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 - arr2)
print(arr1 ** arr2)
print(arr1 % arr2)
print(np.dot(arr1, arr2))

[1. 2. 3.]
[1 2 3]
float64
int32
[1 2 3]
[1. 2. 3.]
[2. 4. 6.]
[1. 4. 9.]
[1. 1. 1.]
[0. 0. 0.]
[ 1.  4. 27.]
[0. 0. 0.]
14.0


In [15]:
rg = np.random.default_rng(1)
print(rg)
print(rg.random(10))

Generator(PCG64)
[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145 0.42332645
 0.82770259 0.40919914 0.54959369 0.02755911]


In [16]:
a = np.ones((2, 3), dtype=int)
print(a)
b = np.ones((2, 3), dtype=float)
print(b)

[[1 1 1]
 [1 1 1]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
import numpy as np
b = rg.random(3,2)
print(b)
a = b.astype(int)
print(a)
a= np.ones((2, 3), )
a= a.astype(str)
print(a)

NameError: name 'rg' is not defined

In [ ]:
import numpy as np
from math import pi
b = np.linspace(0, pi, 3)
print(b)
a= np.array([5, 5, 3])
print(a)
arr= np.array([3,5,3], dtype=np.float64)
print(arr)
arr = np.linspace(7, 5 , 1)
print(arr)
                


            

[0.         1.57079633 3.14159265]
[5 5 3]
[3. 5. 3.]
[7.]


In [ ]:
print(arr)

[7.]


In [ ]:
arr = np.ones((5, 8, 2))
print(arr.shape)
arr.reshape(8, 5, 2)
arr

(5, 8, 2)


array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
arr.reshape(40,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
arr.itemsize
print(arr.itemsize)
arr.nbytes
print(arr.nbytes)
print(arr.dtype)


8
640
float64


In [ ]:
#create 1D array to 2D array to 3D array to 4D array and4D array to 3D array to 2D array to 1D array:


# Create a 1D array
arr_1d = np.arange(24)
print("1D Array:", arr_1d)

# Reshape to 2D (4x6)
arr_2d = arr_1d.reshape(4,6)
print("2D Array:\n", arr_2d)

# Reshape to 3D (2x3x4)
arr_3d = arr_2d.reshape(2,3,4)
print("3D Array:\n", arr_3d)

# Reshape to 4D (2x2x2x3)
arr_4d = arr_3d.reshape(2,2,2,3)
print("4D Array:\n", arr_4d)

# Reshape back from 4D to 3D
arr_back_3d = arr_4d.reshape(2,3,4)
print("Back to 3D Array:\n", arr_back_3d)

# Reshape back from 3D to 2D
arr_back_2d = arr_back_3d.reshape(6,4)
print("Back to 2D Array:\n", arr_back_2d)

# Reshape back from 2D to 1D
arr_back_1d = arr_back_2d.reshape(-1) # -1 means "infer the dimension"
print("Back to 1D Array:", arr_back_1d)

1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
2D Array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
3D Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
4D Array:
 [[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]]
Back to 3D Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Back to 2D Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Back to 1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
#create progam using all keywords and functions used in this numpy tutorial:


# Create arrays with different data types
arr_int = np.array([1, 2, 3, 4, 5], dtype=np.int32)
arr_float = np.array([1.0, 2.0, 3.0], dtype=np.float64)
arr_complex = np.array([1+2j, 3+4j], dtype=np.complex128)

# Print array properties
print("Integer Array:", arr_int)
print("Integer Array Shape:", arr_int.shape)
print("Integer Array Size:", arr_int.size)
print("Integer Array Itemsize:", arr_int.itemsize)
print("Integer Array Nbytes:", arr_int.nbytes)
print("Integer Array Dtype:", arr_int.dtype)

print("\nFloat Array:", arr_float)
print("Float Array Shape:", arr_float.shape)
print("Float Array Size:", arr_float.size)
print("Float Array Itemsize:", arr_float.itemsize)
print("Float Array Nbytes:", arr_float.nbytes)
print("Float Array Dtype:", arr_float.dtype)

print("\nComplex Array:", arr_complex)
print("Complex Array Shape:", arr_complex.shape)
print("Complex Array Size:", arr_complex.size)
print("Complex Array Itemsize:", arr_complex.itemsize)
print("Complex Array Nbytes:", arr_complex.nbytes)
print("Complex Array Dtype:", arr_complex.dtype)

# Reshape arrays
reshaped_1d = np.arange(12).reshape(3,4) # Create a 1D array and reshape it to 2D
reshaped_2d = reshaped_1d.reshape(2,6) # Reshape the 2D array to another 2D array
reshaped_3d = reshaped_2d.reshape(2,3,2) # Reshape the 2D array to a 3D array

# Print reshaped arrays
print("\nOriginal 1D array reshaped to 2D:\n", reshaped_1d)
print("\nReshaped to another 2D array:\n", reshaped_2d)
print("\nReshaped to a 3D array:\n", reshaped_3d)

# Flatten the arrays back to their original shapes
flattened_3d = reshaped_3d.flatten() # Flatten the 3D array back to a 1D array
flattened_2d = reshaped_2d.flatten() # Flatten the 2D array back to a 1D array

# Print flattened arrays
print("\nFlattened back to a 1D array from the original shape:\n", flattened_3d)
print("\nFlattened back to a 1D array from the 2D shape:\n", flattened_2d)


Integer Array: [1 2 3 4 5]
Integer Array Shape: (5,)
Integer Array Size: 5
Integer Array Itemsize: 4
Integer Array Nbytes: 20
Integer Array Dtype: int32

Float Array: [1. 2. 3.]
Float Array Shape: (3,)
Float Array Size: 3
Float Array Itemsize: 8
Float Array Nbytes: 24
Float Array Dtype: float64

Complex Array: [1.+2.j 3.+4.j]
Complex Array Shape: (2,)
Complex Array Size: 2
Complex Array Itemsize: 16
Complex Array Nbytes: 32
Complex Array Dtype: complex128

Original 1D array reshaped to 2D:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to another 2D array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Reshaped to a 3D array:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

Flattened back to a 1D array from the original shape:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Flattened back to a 1D array from the 2D shape:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
#all, any, apply_along_axis, argmax, argmin, argsort, average, create a program using all these functions and keywords:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:\n", arr)

# Using all() function
print("all() function result:", np.all(arr > 0))

# Using any() function
print("any() function result:", np.any(arr < 0))

# Using apply_along_axis() function
print("apply_along_axis() function result:", np.apply_along_axis(np.sum, axis=0, arr=arr))

# Using argmax() function
print("argmax() function result:", np.argmax(arr))

# Using argmin() function
print("argmin() function result:", np.argmin(arr))

# Using argsort() function
print("argsort() function result:", np.argsort(arr.flatten()))

# Using average() function
print("average() function result:", np.average(arr))



Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
all() function result: True
any() function result: False
apply_along_axis() function result: [12 15 18]
argmax() function result: 8
argmin() function result: 0
argsort() function result: [0 1 2 3 4 5 6 7 8]
average() function result: 5.0


In [ ]:
#bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, create a program using all these functions and keywords:


arr = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr)

# Using bincount() function
print("bincount() function result:", np.bincount(arr))

# Using ceil() function
print("ceil() function result:", np.ceil(3.2))

# Using clip() function
print("clip() function result:", np.clip(arr, a_min=2, a_max=4))

# Using conj() function
complex_arr = np.array([1+2j, 3+4j])
print("conj() function result:", np.conj(complex_arr))

# Using corrcoef() function
x = np.array([[0, 2], [2, 3]])
y = np.array([[1, 1], [1, 1]])
print("corrcoef() function result:", np.corrcoef(x, y))

# Using cov() function
print("cov() function result:", np.cov(x))

# Using cross() function
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("cross() function result:", np.cross(a, b))

# Using cumprod() function
print("cumprod() function result:", np.cumprod(arr))

# Using cumsum() function
print("cumsum() function result:", np.cumsum(arr))


Original Array: [1 2 3 4 5]
bincount() function result: [0 1 1 1 1 1]
ceil() function result: 4.0
clip() function result: [2 2 3 4 4]
conj() function result: [1.-2.j 3.-4.j]
corrcoef() function result: [[ 1.  1. nan nan]
 [ 1.  1. nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
cov() function result: [[2.  1. ]
 [1.  0.5]]
cross() function result: [-3  6 -3]
cumprod() function result: [  1   2   6  24 120]
cumsum() function result: [ 1  3  6 10 15]


c:\Users\osm\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
c:\Users\osm\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]


In [ ]:
#diff, dot, floor, inner, invert, lexsort, max, maximum, mean, median, min, minimum, create a program using all these functions and keywords:

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
print("diff() function result:", np.diff(arr1))
print("dot() function result:", np.dot(arr1, arr2))
print("floor() function result:", np.floor(3.7))
print("inner() function result:", np.inner(arr1, arr2))
print("invert() function result:", np.invert(arr1))
print("lexsort() function result:", np.lexsort((arr1, arr2)))
print("max() function result:", np.max(arr1))
print("maximum() function result:", np.maximum(arr1, arr2))
print("mean() function result:", np.mean(arr1))
print("median() function result:", np.median(arr1))
print("min() function result:", np.min(arr1))
print("minimum() function result:", np.minimum(arr1, arr2))


diff() function result: [1 1 1 1]
dot() function result: 35
floor() function result: 3.0
inner() function result: 35
invert() function result: [-2 -3 -4 -5 -6]
lexsort() function result: [4 3 2 1 0]
max() function result: 5
maximum() function result: [5 4 3 4 5]
mean() function result: 3.0
median() function result: 3.0
min() function result: 1
minimum() function result: [1 2 3 2 1]


In [ ]:
# nonzero, outer, prod, re, round, sort, std, sum, swapaxes, take, trace, transpose, unique, var, create a program using all these functions and keywords:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("nonzero() function result:", np.nonzero(arr))
print("outer() function result:", np.outer(arr[0], arr[1]))
print("prod() function result:", np.prod(arr))
print("re() function result:", np.real(arr))
print("round() function result:", np.round(arr, decimals=1))
print("sort() function result:", np.sort(arr, axis=None))
print("std() function result:", np.std(arr))
print("sum() function result:", np.sum(arr))
print("swapaxes() function result:", np.swapaxes(arr, 0, 1))
print("take() function result:", np.take(arr, indices=[0, 2], axis=0))
print("trace() function result:", np.trace(arr))
print("transpose() function result:", np.transpose(arr))
print("unique() function result:", np.unique(arr))
print("var() function result:", np.var(arr))



nonzero() function result: (array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))
outer() function result: [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
prod() function result: 362880
re() function result: [[1 2 3]
 [4 5 6]
 [7 8 9]]
round() function result: [[1 2 3]
 [4 5 6]
 [7 8 9]]
sort() function result: [1 2 3 4 5 6 7 8 9]
std() function result: 2.581988897471611
sum() function result: 45
swapaxes() function result: [[1 4 7]
 [2 5 8]
 [3 6 9]]
take() function result: [[1 2 3]
 [7 8 9]]
trace() function result: 15
transpose() function result: [[1 4 7]
 [2 5 8]
 [3 6 9]]
unique() function result: [1 2 3 4 5 6 7 8 9]
var() function result: 6.666666666666667


In [ ]:
#sum, trace, transpose, var, vdot, vectorize, where create a program using all these functions and keywords:
arr = np.array([[1, 2, 3], [4, 5,
6], [7, 8, 9]])
print("sum() function result:", np.sum(arr))
print("trace() function result:", np.trace(arr))
print("transpose() function result:\n", np.transpose(arr))
print("var() function result:", np.var(arr))
print("vdot() function result:", np.vdot(arr[0], arr[1]))


sum() function result: 45
trace() function result: 15
transpose() function result:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
var() function result: 6.666666666666667
vdot() function result: 32


In [ ]:
arr.dtype
arr.dtype
arr.shape
arr.


SyntaxError: invalid syntax (13509835.py, line 4)

In [ ]:
#create a program using all keywords and functions used in this pandas tutorial:


# Create a sample DataFrame
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
df = pd.DataFrame(data)

# Display the DataFrame
print("Original DataFrame:")
print(df)

# Use various pandas functions and keywords
print("\nDataFrame Info:")
df.info()

print("\nDataFrame Description:")
print(df.describe())

print("\nSelecting specific columns:")
selected_columns = df[['Name', 'Age']]
print(selected_columns)

print("\nFiltering rows based on condition:")
filtered_df = df[df['Age'] > 30]
print(filtered_df)

# Adding a new column
df['Salary'] = [50000, 60000, 70000, 80000]
print("\nDataFrame with Salary column:")
print(df)

# Grouping data
grouped = df.groupby('City')
print("\nGrouped by City:")
for name, group in grouped:
    print(f"City: {name}")
    print(group)



Original DataFrame:
      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Age     4 non-null      int64 
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

DataFrame Description:
             Age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000

Selecting specific columns:
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

Filtering rows based on condition:
      Name  Age     City
2  Charlie   35  Chicago
3    David   40  Houston

DataFrame with Salary column:
      Name  Age         City  Salary
0    Alice   25   

In [ ]:
i